// Generated by BoltFFI — do not edit.
#include "ruby.h"
#include "ruby/encoding.h"
#include "ruby/ractor.h"
#include <stdint.h>
#include <limits.h>
#include <string.h>

typedef struct { const uint8_t *ptr; uintptr_t len; } FfiString;
typedef struct { const uint8_t *ptr; uintptr_t len; } FfiBytes;
typedef struct { uint8_t *ptr; uintptr_t len; uintptr_t cap; uintptr_t align; } FfiBuf;
extern void boltffi_free_buf(FfiBuf);

static inline FfiString bolt_rb_to_ffi_string(VALUE v) {
    FfiString s; s.ptr = (const uint8_t*)RSTRING_PTR(v); s.len = (uintptr_t)RSTRING_LEN(v); return s;
}
static inline FfiBytes bolt_rb_to_ffi_bytes(VALUE v) {
    FfiBytes b; b.ptr = (const uint8_t*)RSTRING_PTR(v); b.len = (uintptr_t)RSTRING_LEN(v); return b;
}


typedef struct DataConsumer DataConsumer;
typedef struct AsyncWorker AsyncWorker;
typedef struct ConstructorCoverageMatrix ConstructorCoverageMatrix;
typedef struct Inventory Inventory;
typedef struct Counter Counter;
typedef struct MixedRecordService MixedRecordService;
typedef struct MathUtils MathUtils;
typedef struct EventBus EventBus;
typedef struct SharedCounter SharedCounter;
typedef struct DataStore DataStore;
typedef struct Accumulator Accumulator;
typedef struct Marker Marker;
typedef struct MapView MapView;
typedef struct StateHolder StateHolder;
typedef struct CounterSingleThreaded CounterSingleThreaded;
typedef struct AccumulatorSingleThreaded AccumulatorSingleThreaded;

static VALUE c_data_consumer;
static const rb_data_type_t data_consumer_type;
static VALUE c_async_worker;
static const rb_data_type_t async_worker_type;
static VALUE c_constructor_coverage_matrix;
static const rb_data_type_t constructor_coverage_matrix_type;
static VALUE c_inventory;
static const rb_data_type_t inventory_type;
static VALUE c_counter;
static const rb_data_type_t counter_type;
static VALUE c_mixed_record_service;
static const rb_data_type_t mixed_record_service_type;
static VALUE c_math_utils;
static const rb_data_type_t math_utils_type;
static VALUE c_event_bus;
static const rb_data_type_t event_bus_type;
static VALUE c_shared_counter;
static const rb_data_type_t shared_counter_type;
static VALUE c_data_store;
static const rb_data_type_t data_store_type;
static VALUE c_accumulator;
static const rb_data_type_t accumulator_type;
static VALUE c_marker;
static const rb_data_type_t marker_type;
static VALUE c_map_view;
static const rb_data_type_t map_view_type;
static VALUE c_state_holder;
static const rb_data_type_t state_holder_type;
static VALUE c_counter_single_threaded;
static const rb_data_type_t counter_single_threaded_type;
static VALUE c_accumulator_single_threaded;
static const rb_data_type_t accumulator_single_threaded_type;

static void data_consumer_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_data_consumer_free(DataConsumer*);
        boltffi_data_consumer_free((DataConsumer*)p);
    }
}
static void async_worker_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_async_worker_free(AsyncWorker*);
        boltffi_async_worker_free((AsyncWorker*)p);
    }
}
static void constructor_coverage_matrix_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_constructor_coverage_matrix_free(ConstructorCoverageMatrix*);
        boltffi_constructor_coverage_matrix_free((ConstructorCoverageMatrix*)p);
    }
}
static void inventory_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_inventory_free(Inventory*);
        boltffi_inventory_free((Inventory*)p);
    }
}
static void counter_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_counter_free(Counter*);
        boltffi_counter_free((Counter*)p);
    }
}
static void mixed_record_service_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_mixed_record_service_free(MixedRecordService*);
        boltffi_mixed_record_service_free((MixedRecordService*)p);
    }
}
static void math_utils_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_math_utils_free(MathUtils*);
        boltffi_math_utils_free((MathUtils*)p);
    }
}
static void event_bus_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_event_bus_free(EventBus*);
        boltffi_event_bus_free((EventBus*)p);
    }
}
static void shared_counter_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_shared_counter_free(SharedCounter*);
        boltffi_shared_counter_free((SharedCounter*)p);
    }
}
static void data_store_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_data_store_free(DataStore*);
        boltffi_data_store_free((DataStore*)p);
    }
}
static void accumulator_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_accumulator_free(Accumulator*);
        boltffi_accumulator_free((Accumulator*)p);
    }
}
static void marker_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_marker_free(Marker*);
        boltffi_marker_free((Marker*)p);
    }
}
static void map_view_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_map_view_free(MapView*);
        boltffi_map_view_free((MapView*)p);
    }
}
static void state_holder_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_state_holder_free(StateHolder*);
        boltffi_state_holder_free((StateHolder*)p);
    }
}
static void counter_single_threaded_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_counter_single_threaded_free(CounterSingleThreaded*);
        boltffi_counter_single_threaded_free((CounterSingleThreaded*)p);
    }
}
static void accumulator_single_threaded_dfree(void *p) {
    if (p != NULL) {
        extern void boltffi_accumulator_single_threaded_free(AccumulatorSingleThreaded*);
        boltffi_accumulator_single_threaded_free((AccumulatorSingleThreaded*)p);
    }
}

static const rb_data_type_t data_consumer_type = {
    "demo::DataConsumer",
    { NULL, data_consumer_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t async_worker_type = {
    "demo::AsyncWorker",
    { NULL, async_worker_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t constructor_coverage_matrix_type = {
    "demo::ConstructorCoverageMatrix",
    { NULL, constructor_coverage_matrix_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t inventory_type = {
    "demo::Inventory",
    { NULL, inventory_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t counter_type = {
    "demo::Counter",
    { NULL, counter_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t mixed_record_service_type = {
    "demo::MixedRecordService",
    { NULL, mixed_record_service_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t math_utils_type = {
    "demo::MathUtils",
    { NULL, math_utils_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t event_bus_type = {
    "demo::EventBus",
    { NULL, event_bus_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t shared_counter_type = {
    "demo::SharedCounter",
    { NULL, shared_counter_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t data_store_type = {
    "demo::DataStore",
    { NULL, data_store_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t accumulator_type = {
    "demo::Accumulator",
    { NULL, accumulator_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t marker_type = {
    "demo::Marker",
    { NULL, marker_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t map_view_type = {
    "demo::MapView",
    { NULL, map_view_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t state_holder_type = {
    "demo::StateHolder",
    { NULL, state_holder_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t counter_single_threaded_type = {
    "demo::CounterSingleThreaded",
    { NULL, counter_single_threaded_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};
static const rb_data_type_t accumulator_single_threaded_type = {
    "demo::AccumulatorSingleThreaded",
    { NULL, accumulator_single_threaded_dfree, NULL, NULL },
    NULL, NULL, RUBY_TYPED_FREE_IMMEDIATELY,
};


extern void boltffi_echo_duration(VALUE);
extern void boltffi_make_duration(uint64_t, uint32_t);
extern uint64_t boltffi_duration_as_millis(VALUE);
extern void boltffi_echo_system_time(VALUE);
extern uint64_t boltffi_system_time_to_millis(VALUE);
extern void boltffi_millis_to_system_time(uint64_t);
extern void boltffi_echo_uuid(VALUE);
extern FfiBuf boltffi_uuid_to_string(VALUE);
extern void boltffi_echo_url(VALUE);
extern FfiBuf boltffi_url_to_string(VALUE);
extern FfiBuf boltffi_echo_bytes(FfiBytes);
extern uint32_t boltffi_bytes_length(FfiBytes);
extern uint32_t boltffi_bytes_sum(FfiBytes);
extern FfiBuf boltffi_make_bytes(uint32_t);
extern FfiBuf boltffi_reverse_bytes(FfiBytes);
extern FfiBuf boltffi_generate_bytes(int32_t);
extern int32_t boltffi_apply_closure(VALUE, int32_t);
extern int32_t boltffi_apply_binary_closure(VALUE, int32_t, int32_t);
extern void boltffi_apply_void_closure(VALUE, int32_t);
extern int32_t boltffi_apply_nullary_closure(VALUE);
extern FfiBuf boltffi_apply_string_closure(VALUE, FfiString);
extern int boltffi_apply_bool_closure(VALUE, int);
extern double boltffi_apply_f64_closure(VALUE, double);
extern int64_t boltffi_apply_offset_closure(VALUE, int64_t, uint64_t);
extern int32_t boltffi_apply_status_closure(VALUE, int32_t);
extern int32_t boltffi_invoke_value_callback(VALUE, int32_t);
extern int32_t boltffi_invoke_value_callback_twice(VALUE, int32_t, int32_t);
extern int32_t boltffi_invoke_boxed_value_callback(VALUE, int32_t);
extern void boltffi_make_incrementing_callback(int32_t);
extern int32_t boltffi_map_status(VALUE, int32_t);
extern void boltffi_make_status_flipper(void);
extern FfiBuf boltffi_format_message_with_callback(VALUE, FfiString, FfiString);
extern FfiBuf boltffi_format_message_with_boxed_callback(VALUE, FfiString, FfiString);
extern void boltffi_make_message_prefixer(FfiString);
extern int32_t boltffi_invoke_multi_method(VALUE, int32_t, int32_t);
extern int32_t boltffi_invoke_multi_method_boxed(VALUE, int32_t, int32_t);
extern int32_t boltffi_invoke_two_callbacks(VALUE, VALUE, int32_t);
extern int64_t boltffi_invoke_offset_callback(VALUE, int64_t, uint64_t);
extern int64_t boltffi_invoke_boxed_offset_callback(VALUE, int64_t, uint64_t);
extern void boltffi_echo_email(VALUE);
extern FfiBuf boltffi_email_domain(VALUE);
extern void boltffi_echo_datetime(VALUE);
extern int64_t boltffi_datetime_to_millis(VALUE);
extern FfiBuf boltffi_format_timestamp(VALUE);
extern int32_t boltffi_echo_status(int32_t);
extern FfiBuf boltffi_status_to_string(int32_t);
extern int boltffi_is_active(int32_t);
extern int32_t boltffi_echo_direction(int32_t);
extern int32_t boltffi_opposite_direction(int32_t);
extern int32_t boltffi_direction_to_degrees(int32_t);
extern int32_t boltffi_echo_filter(int32_t);
extern FfiBuf boltffi_describe_filter(int32_t);
extern int32_t boltffi_echo_api_response(int32_t);
extern int boltffi_is_success(int32_t);
extern int32_t boltffi_echo_shape(int32_t);
extern int32_t boltffi_make_circle(double);
extern int32_t boltffi_make_rectangle(double, double);
extern int32_t boltffi_echo_message(int32_t);
extern FfiBuf boltffi_message_summary(int32_t);
extern int32_t boltffi_echo_animal(int32_t);
extern FfiBuf boltffi_animal_name(int32_t);
extern int32_t boltffi_echo_task_status(int32_t);
extern int32_t boltffi_get_status_progress(int32_t);
extern int boltffi_is_status_complete(int32_t);
extern int32_t boltffi_echo_lifecycle_event(int32_t);
extern int32_t boltffi_make_critical_lifecycle_event(int64_t);
extern int32_t boltffi_echo_priority(int32_t);
extern FfiBuf boltffi_priority_label(int32_t);
extern int boltffi_is_high_priority(int32_t);
extern int32_t boltffi_echo_log_level(int32_t);
extern int boltffi_should_log(int32_t, int32_t);
extern int32_t boltffi_echo_http_code(int32_t);
extern int32_t boltffi_http_code_not_found(void);
extern int32_t boltffi_echo_sign(int32_t);
extern int32_t boltffi_sign_negative(void);
extern int boltffi_echo_bool(int);
extern int boltffi_negate_bool(int);
extern int8_t boltffi_echo_i8(int8_t);
extern uint8_t boltffi_echo_u8(uint8_t);
extern int16_t boltffi_echo_i16(int16_t);
extern uint16_t boltffi_echo_u16(uint16_t);
extern int32_t boltffi_echo_i32(int32_t);
extern int32_t boltffi_add_i32(int32_t, int32_t);
extern uint32_t boltffi_echo_u32(uint32_t);
extern int64_t boltffi_echo_i64(int64_t);
extern uint64_t boltffi_echo_u64(uint64_t);
extern float boltffi_echo_f32(float);
extern float boltffi_add_f32(float, float);
extern double boltffi_echo_f64(double);
extern double boltffi_add_f64(double, double);
extern uint64_t boltffi_echo_usize(uint64_t);
extern int64_t boltffi_echo_isize(int64_t);
extern void boltffi_noop(void);
extern int32_t boltffi_add(int32_t, int32_t);
extern double boltffi_multiply(double, double);
extern FfiBuf boltffi_echo_string(FfiString);
extern FfiBuf boltffi_concat_strings(FfiString, FfiString);
extern uint32_t boltffi_string_length(FfiString);
extern int boltffi_string_is_empty(FfiString);
extern FfiBuf boltffi_repeat_string(FfiString, uint32_t);
extern FfiBuf boltffi_generate_string(int32_t);
extern FfiBuf boltffi_echo_vec_u8(FfiBytes);
extern uint64_t boltffi_inc_u64_value(uint64_t);
extern FfiBuf boltffi_result_to_string(VALUE);
extern int32_t boltffi_process_value(int32_t);
extern int boltffi_api_result_is_success(int32_t);

extern DataConsumer* boltffi_data_consumer_new(void);
extern AsyncWorker* boltffi_async_worker_new(FfiString);
extern ConstructorCoverageMatrix* boltffi_constructor_coverage_matrix_new(void);
extern ConstructorCoverageMatrix* boltffi_constructor_coverage_matrix_with_scalar_mix(uint32_t, int, int32_t);
extern ConstructorCoverageMatrix* boltffi_constructor_coverage_matrix_with_string_and_bytes(FfiString, FfiBytes);
extern Inventory* boltffi_inventory_new(void);
extern Inventory* boltffi_inventory_with_capacity(uint32_t);
extern Inventory* boltffi_inventory_try_new(uint32_t);
extern Counter* boltffi_counter_new(int32_t);
extern MixedRecordService* boltffi_mixed_record_service_new(FfiString);
extern MathUtils* boltffi_math_utils_new(uint32_t);
extern EventBus* boltffi_event_bus_new(void);
extern SharedCounter* boltffi_shared_counter_new(int32_t);
extern DataStore* boltffi_data_store_new(void);
extern DataStore* boltffi_data_store_with_sample_data(void);
extern DataStore* boltffi_data_store_with_capacity(int32_t);
extern DataStore* boltffi_data_store_with_initial_point(double, double, int64_t);
extern Accumulator* boltffi_accumulator_new(void);
extern MapView* boltffi_map_view_new(void);
extern StateHolder* boltffi_state_holder_new(FfiString);
extern CounterSingleThreaded* boltffi_counter_single_threaded_new(void);
extern AccumulatorSingleThreaded* boltffi_accumulator_single_threaded_new(void);

extern void boltffi_data_consumer_set_provider(DataConsumer*, VALUE);
extern uint64_t boltffi_data_consumer_compute_sum(DataConsumer*);
extern FfiBuf boltffi_async_worker_get_prefix(AsyncWorker*);
extern FfiBuf boltffi_constructor_coverage_matrix_constructor_variant(ConstructorCoverageMatrix*);
extern FfiBuf boltffi_constructor_coverage_matrix_summary(ConstructorCoverageMatrix*);
extern uint32_t boltffi_constructor_coverage_matrix_payload_checksum(ConstructorCoverageMatrix*);
extern uint32_t boltffi_constructor_coverage_matrix_vector_count(ConstructorCoverageMatrix*);
extern uint32_t boltffi_inventory_count(Inventory*);
extern uint32_t boltffi_inventory_capacity(Inventory*);
extern int boltffi_inventory_add(Inventory*, FfiString);
extern int32_t boltffi_counter_get(Counter*);
extern void boltffi_counter_increment(Counter*);
extern void boltffi_counter_add(Counter*, int32_t);
extern void boltffi_counter_reset(Counter*);
extern FfiBuf boltffi_mixed_record_service_get_label(MixedRecordService*);
extern uint32_t boltffi_mixed_record_service_stored_count(MixedRecordService*);
extern double boltffi_math_utils_round(MathUtils*, double);
extern int32_t boltffi_math_utils_add(int32_t, int32_t);
extern double boltffi_math_utils_clamp(double, double, double);
extern void boltffi_event_bus_emit_value(EventBus*, int32_t);
extern int32_t boltffi_shared_counter_get(SharedCounter*);
extern void boltffi_shared_counter_set(SharedCounter*, int32_t);
extern int32_t boltffi_shared_counter_increment(SharedCounter*);
extern int32_t boltffi_shared_counter_add(SharedCounter*, int32_t);
extern void boltffi_data_store_add_parts(DataStore*, double, double, int64_t);
extern uint64_t boltffi_data_store_len(DataStore*);
extern int boltffi_data_store_is_empty(DataStore*);
extern double boltffi_data_store_sum(DataStore*);
extern void boltffi_data_store_foreach(DataStore*, VALUE);
extern void boltffi_accumulator_add(Accumulator*, int64_t);
extern int64_t boltffi_accumulator_get(Accumulator*);
extern void boltffi_accumulator_reset(Accumulator*);
extern uint32_t boltffi_marker_id(Marker*);
extern FfiBuf boltffi_marker_title(Marker*);
extern uint32_t boltffi_map_view_marker_count(MapView*);
extern FfiBuf boltffi_state_holder_get_label(StateHolder*);
extern int32_t boltffi_state_holder_get_value(StateHolder*);
extern uint32_t boltffi_state_holder_item_count(StateHolder*);
extern int32_t boltffi_counter_single_threaded_get(CounterSingleThreaded*);
extern int64_t boltffi_accumulator_single_threaded_get(AccumulatorSingleThreaded*);


static VALUE data_consumer_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &data_consumer_type, NULL);
}

static VALUE data_consumer_initialize(VALUE self) {
    DataConsumer* ptr = boltffi_data_consumer_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE data_consumer_set_provider(VALUE self, VALUE provider) {
    DataConsumer* handle = rb_check_typeddata(self, &data_consumer_type);
    boltffi_data_consumer_set_provider(handle, (provider));

    return Qnil;

}
static VALUE data_consumer_compute_sum(VALUE self) {
    DataConsumer* handle = rb_check_typeddata(self, &data_consumer_type);
    uint64_t _ffi_ret = boltffi_data_consumer_compute_sum(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}


static VALUE async_worker_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &async_worker_type, NULL);
}

static VALUE async_worker_initialize(VALUE self, VALUE prefix) {
    Check_Type(prefix, T_STRING);
    AsyncWorker* ptr = boltffi_async_worker_new(bolt_rb_to_ffi_string(prefix));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE async_worker_get_prefix(VALUE self) {
    AsyncWorker* handle = rb_check_typeddata(self, &async_worker_type);
    FfiBuf _ffi_ret = boltffi_async_worker_get_prefix(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}


static VALUE constructor_coverage_matrix_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &constructor_coverage_matrix_type, NULL);
}

static VALUE constructor_coverage_matrix_initialize(VALUE self) {
    ConstructorCoverageMatrix* ptr = boltffi_constructor_coverage_matrix_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE constructor_coverage_matrix_ctor_with_scalar_mix(VALUE klass, VALUE version, VALUE enabled, VALUE priority) {
    ConstructorCoverageMatrix* ptr = boltffi_constructor_coverage_matrix_with_scalar_mix(NUM2UINT(version), RB_TEST(enabled), NUM2INT(priority));
    return TypedData_Wrap_Struct(klass, &constructor_coverage_matrix_type, ptr);
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE constructor_coverage_matrix_ctor_with_string_and_bytes(VALUE klass, VALUE label, VALUE payload) {
    Check_Type(label, T_STRING);
    Check_Type(payload, T_STRING);
    ConstructorCoverageMatrix* ptr = boltffi_constructor_coverage_matrix_with_string_and_bytes(bolt_rb_to_ffi_string(label), bolt_rb_to_ffi_bytes(payload));
    return TypedData_Wrap_Struct(klass, &constructor_coverage_matrix_type, ptr);
}

static VALUE constructor_coverage_matrix_constructor_variant(VALUE self) {
    ConstructorCoverageMatrix* handle = rb_check_typeddata(self, &constructor_coverage_matrix_type);
    FfiBuf _ffi_ret = boltffi_constructor_coverage_matrix_constructor_variant(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE constructor_coverage_matrix_summary(VALUE self) {
    ConstructorCoverageMatrix* handle = rb_check_typeddata(self, &constructor_coverage_matrix_type);
    FfiBuf _ffi_ret = boltffi_constructor_coverage_matrix_summary(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE constructor_coverage_matrix_payload_checksum(VALUE self) {
    ConstructorCoverageMatrix* handle = rb_check_typeddata(self, &constructor_coverage_matrix_type);
    uint32_t _ffi_ret = boltffi_constructor_coverage_matrix_payload_checksum(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE constructor_coverage_matrix_vector_count(VALUE self) {
    ConstructorCoverageMatrix* handle = rb_check_typeddata(self, &constructor_coverage_matrix_type);
    uint32_t _ffi_ret = boltffi_constructor_coverage_matrix_vector_count(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}


static VALUE inventory_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &inventory_type, NULL);
}

static VALUE inventory_initialize(VALUE self) {
    Inventory* ptr = boltffi_inventory_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE inventory_ctor_with_capacity(VALUE klass, VALUE capacity) {
    Inventory* ptr = boltffi_inventory_with_capacity(NUM2UINT(capacity));
    return TypedData_Wrap_Struct(klass, &inventory_type, ptr);
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE inventory_ctor_try_new(VALUE klass, VALUE capacity) {
    Inventory* ptr = boltffi_inventory_try_new(NUM2UINT(capacity));
    if (ptr == NULL) {
        extern void boltffi_last_error_message(FfiString* out);
        FfiString msg;
        boltffi_last_error_message(&msg);
        rb_raise(rb_eRuntimeError, "%.*s", (int)msg.len, (const char*)msg.ptr);
    }
    return TypedData_Wrap_Struct(klass, &inventory_type, ptr);
}

static VALUE inventory_count(VALUE self) {
    Inventory* handle = rb_check_typeddata(self, &inventory_type);
    uint32_t _ffi_ret = boltffi_inventory_count(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE inventory_capacity(VALUE self) {
    Inventory* handle = rb_check_typeddata(self, &inventory_type);
    uint32_t _ffi_ret = boltffi_inventory_capacity(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE inventory_add(VALUE self, VALUE item) {
    Inventory* handle = rb_check_typeddata(self, &inventory_type);
    Check_Type(item, T_STRING);
    int _ffi_ret = boltffi_inventory_add(handle, bolt_rb_to_ffi_string(item));

    return _ffi_ret ? Qtrue : Qfalse;

}


static VALUE counter_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &counter_type, NULL);
}

static VALUE counter_initialize(VALUE self, VALUE initial) {
    Counter* ptr = boltffi_counter_new(NUM2INT(initial));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE counter_get(VALUE self) {
    Counter* handle = rb_check_typeddata(self, &counter_type);
    int32_t _ffi_ret = boltffi_counter_get(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE counter_increment(VALUE self) {
    Counter* handle = rb_check_typeddata(self, &counter_type);
    boltffi_counter_increment(handle);

    return Qnil;

}
static VALUE counter_add(VALUE self, VALUE amount) {
    Counter* handle = rb_check_typeddata(self, &counter_type);
    boltffi_counter_add(handle, NUM2INT(amount));

    return Qnil;

}
static VALUE counter_reset(VALUE self) {
    Counter* handle = rb_check_typeddata(self, &counter_type);
    boltffi_counter_reset(handle);

    return Qnil;

}


static VALUE mixed_record_service_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &mixed_record_service_type, NULL);
}

static VALUE mixed_record_service_initialize(VALUE self, VALUE label) {
    Check_Type(label, T_STRING);
    MixedRecordService* ptr = boltffi_mixed_record_service_new(bolt_rb_to_ffi_string(label));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE mixed_record_service_get_label(VALUE self) {
    MixedRecordService* handle = rb_check_typeddata(self, &mixed_record_service_type);
    FfiBuf _ffi_ret = boltffi_mixed_record_service_get_label(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE mixed_record_service_stored_count(VALUE self) {
    MixedRecordService* handle = rb_check_typeddata(self, &mixed_record_service_type);
    uint32_t _ffi_ret = boltffi_mixed_record_service_stored_count(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}


static VALUE math_utils_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &math_utils_type, NULL);
}

static VALUE math_utils_initialize(VALUE self, VALUE precision) {
    MathUtils* ptr = boltffi_math_utils_new(NUM2UINT(precision));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE math_utils_round(VALUE self, VALUE value) {
    MathUtils* handle = rb_check_typeddata(self, &math_utils_type);
    double _ffi_ret = boltffi_math_utils_round(handle, NUM2DBL(value));

    return rb_float_new(_ffi_ret);

}
static VALUE math_utils_add(VALUE self, VALUE a, VALUE b) {
    (void)self; // static method: `self` is the class object, unused
    int32_t _ffi_ret = boltffi_math_utils_add(NUM2INT(a), NUM2INT(b));

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE math_utils_clamp(VALUE self, VALUE value, VALUE min, VALUE max) {
    (void)self; // static method: `self` is the class object, unused
    double _ffi_ret = boltffi_math_utils_clamp(NUM2DBL(value), NUM2DBL(min), NUM2DBL(max));

    return rb_float_new(_ffi_ret);

}


static VALUE event_bus_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &event_bus_type, NULL);
}

static VALUE event_bus_initialize(VALUE self) {
    EventBus* ptr = boltffi_event_bus_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE event_bus_emit_value(VALUE self, VALUE value) {
    EventBus* handle = rb_check_typeddata(self, &event_bus_type);
    boltffi_event_bus_emit_value(handle, NUM2INT(value));

    return Qnil;

}


static VALUE shared_counter_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &shared_counter_type, NULL);
}

static VALUE shared_counter_initialize(VALUE self, VALUE initial) {
    SharedCounter* ptr = boltffi_shared_counter_new(NUM2INT(initial));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE shared_counter_get(VALUE self) {
    SharedCounter* handle = rb_check_typeddata(self, &shared_counter_type);
    int32_t _ffi_ret = boltffi_shared_counter_get(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE shared_counter_set(VALUE self, VALUE value) {
    SharedCounter* handle = rb_check_typeddata(self, &shared_counter_type);
    boltffi_shared_counter_set(handle, NUM2INT(value));

    return Qnil;

}
static VALUE shared_counter_increment(VALUE self) {
    SharedCounter* handle = rb_check_typeddata(self, &shared_counter_type);
    int32_t _ffi_ret = boltffi_shared_counter_increment(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE shared_counter_add(VALUE self, VALUE amount) {
    SharedCounter* handle = rb_check_typeddata(self, &shared_counter_type);
    int32_t _ffi_ret = boltffi_shared_counter_add(handle, NUM2INT(amount));

    return rb_int2inum((intptr_t)_ffi_ret);

}


static VALUE data_store_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &data_store_type, NULL);
}

static VALUE data_store_initialize(VALUE self) {
    DataStore* ptr = boltffi_data_store_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE data_store_ctor_with_sample_data(VALUE klass) {
    DataStore* ptr = boltffi_data_store_with_sample_data();
    return TypedData_Wrap_Struct(klass, &data_store_type, ptr);
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE data_store_ctor_with_capacity(VALUE klass, VALUE capacity) {
    DataStore* ptr = boltffi_data_store_with_capacity(NUM2INT(capacity));
    return TypedData_Wrap_Struct(klass, &data_store_type, ptr);
}
// Named constructor — defined as a singleton (class) method that allocates and
// wraps the Rust handle directly, rather than the alloc+initialize pair `new` uses.
static VALUE data_store_ctor_with_initial_point(VALUE klass, VALUE x, VALUE y, VALUE timestamp) {
    DataStore* ptr = boltffi_data_store_with_initial_point(NUM2DBL(x), NUM2DBL(y), NUM2LL(timestamp));
    return TypedData_Wrap_Struct(klass, &data_store_type, ptr);
}

static VALUE data_store_add_parts(VALUE self, VALUE x, VALUE y, VALUE timestamp) {
    DataStore* handle = rb_check_typeddata(self, &data_store_type);
    boltffi_data_store_add_parts(handle, NUM2DBL(x), NUM2DBL(y), NUM2LL(timestamp));

    return Qnil;

}
static VALUE data_store_len(VALUE self) {
    DataStore* handle = rb_check_typeddata(self, &data_store_type);
    uint64_t _ffi_ret = boltffi_data_store_len(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE data_store_is_empty(VALUE self) {
    DataStore* handle = rb_check_typeddata(self, &data_store_type);
    int _ffi_ret = boltffi_data_store_is_empty(handle);

    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE data_store_sum(VALUE self) {
    DataStore* handle = rb_check_typeddata(self, &data_store_type);
    double _ffi_ret = boltffi_data_store_sum(handle);

    return rb_float_new(_ffi_ret);

}
static VALUE data_store_foreach(VALUE self, VALUE callback) {
    DataStore* handle = rb_check_typeddata(self, &data_store_type);
    boltffi_data_store_foreach(handle, (callback));

    return Qnil;

}


static VALUE accumulator_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &accumulator_type, NULL);
}

static VALUE accumulator_initialize(VALUE self) {
    Accumulator* ptr = boltffi_accumulator_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE accumulator_add(VALUE self, VALUE amount) {
    Accumulator* handle = rb_check_typeddata(self, &accumulator_type);
    boltffi_accumulator_add(handle, NUM2LL(amount));

    return Qnil;

}
static VALUE accumulator_get(VALUE self) {
    Accumulator* handle = rb_check_typeddata(self, &accumulator_type);
    int64_t _ffi_ret = boltffi_accumulator_get(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE accumulator_reset(VALUE self) {
    Accumulator* handle = rb_check_typeddata(self, &accumulator_type);
    boltffi_accumulator_reset(handle);

    return Qnil;

}


static VALUE marker_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &marker_type, NULL);
}


static VALUE marker_id(VALUE self) {
    Marker* handle = rb_check_typeddata(self, &marker_type);
    uint32_t _ffi_ret = boltffi_marker_id(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE marker_title(VALUE self) {
    Marker* handle = rb_check_typeddata(self, &marker_type);
    FfiBuf _ffi_ret = boltffi_marker_title(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}


static VALUE map_view_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &map_view_type, NULL);
}

static VALUE map_view_initialize(VALUE self) {
    MapView* ptr = boltffi_map_view_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE map_view_marker_count(VALUE self) {
    MapView* handle = rb_check_typeddata(self, &map_view_type);
    uint32_t _ffi_ret = boltffi_map_view_marker_count(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}


static VALUE state_holder_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &state_holder_type, NULL);
}

static VALUE state_holder_initialize(VALUE self, VALUE label) {
    Check_Type(label, T_STRING);
    StateHolder* ptr = boltffi_state_holder_new(bolt_rb_to_ffi_string(label));
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE state_holder_get_label(VALUE self) {
    StateHolder* handle = rb_check_typeddata(self, &state_holder_type);
    FfiBuf _ffi_ret = boltffi_state_holder_get_label(handle);
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE state_holder_get_value(VALUE self) {
    StateHolder* handle = rb_check_typeddata(self, &state_holder_type);
    int32_t _ffi_ret = boltffi_state_holder_get_value(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE state_holder_item_count(VALUE self) {
    StateHolder* handle = rb_check_typeddata(self, &state_holder_type);
    uint32_t _ffi_ret = boltffi_state_holder_item_count(handle);

    return rb_uint2inum((uintptr_t)_ffi_ret);

}


static VALUE counter_single_threaded_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &counter_single_threaded_type, NULL);
}

static VALUE counter_single_threaded_initialize(VALUE self) {
    CounterSingleThreaded* ptr = boltffi_counter_single_threaded_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE counter_single_threaded_get(VALUE self) {
    CounterSingleThreaded* handle = rb_check_typeddata(self, &counter_single_threaded_type);
    int32_t _ffi_ret = boltffi_counter_single_threaded_get(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}


static VALUE accumulator_single_threaded_alloc(VALUE klass) {
    return TypedData_Wrap_Struct(klass, &accumulator_single_threaded_type, NULL);
}

static VALUE accumulator_single_threaded_initialize(VALUE self) {
    AccumulatorSingleThreaded* ptr = boltffi_accumulator_single_threaded_new();
    RTYPEDDATA_DATA(self) = ptr;
    return self;
}

static VALUE accumulator_single_threaded_get(VALUE self) {
    AccumulatorSingleThreaded* handle = rb_check_typeddata(self, &accumulator_single_threaded_type);
    int64_t _ffi_ret = boltffi_accumulator_single_threaded_get(handle);

    return rb_int2inum((intptr_t)_ffi_ret);

}



static VALUE rb_echo_duration(VALUE self, VALUE d) {
    boltffi_echo_duration((d));
    return Qnil;

}
static VALUE rb_make_duration(VALUE self, VALUE secs, VALUE nanos) {
    boltffi_make_duration(NUM2ULL(secs), NUM2UINT(nanos));
    return Qnil;

}
static VALUE rb_duration_as_millis(VALUE self, VALUE d) {
    uint64_t _ffi_ret = boltffi_duration_as_millis((d));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_system_time(VALUE self, VALUE t) {
    boltffi_echo_system_time((t));
    return Qnil;

}
static VALUE rb_system_time_to_millis(VALUE self, VALUE t) {
    uint64_t _ffi_ret = boltffi_system_time_to_millis((t));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_millis_to_system_time(VALUE self, VALUE millis) {
    boltffi_millis_to_system_time(NUM2ULL(millis));
    return Qnil;

}
static VALUE rb_echo_uuid(VALUE self, VALUE id) {
    boltffi_echo_uuid((id));
    return Qnil;

}
static VALUE rb_uuid_to_string(VALUE self, VALUE id) {
    FfiBuf _ffi_ret = boltffi_uuid_to_string((id));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_url(VALUE self, VALUE url) {
    boltffi_echo_url((url));
    return Qnil;

}
static VALUE rb_url_to_string(VALUE self, VALUE url) {
    FfiBuf _ffi_ret = boltffi_url_to_string((url));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_bytes(VALUE self, VALUE data) {
    Check_Type(data, T_STRING);
    FfiBuf _ffi_ret = boltffi_echo_bytes(bolt_rb_to_ffi_bytes(data));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_bytes_length(VALUE self, VALUE data) {
    Check_Type(data, T_STRING);
    uint32_t _ffi_ret = boltffi_bytes_length(bolt_rb_to_ffi_bytes(data));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_bytes_sum(VALUE self, VALUE data) {
    Check_Type(data, T_STRING);
    uint32_t _ffi_ret = boltffi_bytes_sum(bolt_rb_to_ffi_bytes(data));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_make_bytes(VALUE self, VALUE len) {
    FfiBuf _ffi_ret = boltffi_make_bytes(NUM2UINT(len));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_reverse_bytes(VALUE self, VALUE data) {
    Check_Type(data, T_STRING);
    FfiBuf _ffi_ret = boltffi_reverse_bytes(bolt_rb_to_ffi_bytes(data));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_generate_bytes(VALUE self, VALUE size) {
    FfiBuf _ffi_ret = boltffi_generate_bytes(NUM2INT(size));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_apply_closure(VALUE self, VALUE f, VALUE value) {
    int32_t _ffi_ret = boltffi_apply_closure((f), NUM2INT(value));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_apply_binary_closure(VALUE self, VALUE f, VALUE a, VALUE b) {
    int32_t _ffi_ret = boltffi_apply_binary_closure((f), NUM2INT(a), NUM2INT(b));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_apply_void_closure(VALUE self, VALUE f, VALUE value) {
    boltffi_apply_void_closure((f), NUM2INT(value));
    return Qnil;

}
static VALUE rb_apply_nullary_closure(VALUE self, VALUE f) {
    int32_t _ffi_ret = boltffi_apply_nullary_closure((f));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_apply_string_closure(VALUE self, VALUE f, VALUE s) {
    Check_Type(s, T_STRING);
    FfiBuf _ffi_ret = boltffi_apply_string_closure((f), bolt_rb_to_ffi_string(s));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_apply_bool_closure(VALUE self, VALUE f, VALUE v) {
    int _ffi_ret = boltffi_apply_bool_closure((f), RB_TEST(v));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_apply_f64_closure(VALUE self, VALUE f, VALUE v) {
    double _ffi_ret = boltffi_apply_f64_closure((f), NUM2DBL(v));
    return rb_float_new(_ffi_ret);

}
static VALUE rb_apply_offset_closure(VALUE self, VALUE f, VALUE value, VALUE delta) {
    int64_t _ffi_ret = boltffi_apply_offset_closure((f), NUM2LL(value), NUM2ULL(delta));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_apply_status_closure(VALUE self, VALUE f, VALUE status) {
    int32_t _ffi_ret = boltffi_apply_status_closure((f), NUM2INT(status));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_value_callback(VALUE self, VALUE callback, VALUE input) {
    int32_t _ffi_ret = boltffi_invoke_value_callback((callback), NUM2INT(input));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_value_callback_twice(VALUE self, VALUE callback, VALUE a, VALUE b) {
    int32_t _ffi_ret = boltffi_invoke_value_callback_twice((callback), NUM2INT(a), NUM2INT(b));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_boxed_value_callback(VALUE self, VALUE callback, VALUE input) {
    int32_t _ffi_ret = boltffi_invoke_boxed_value_callback((callback), NUM2INT(input));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_make_incrementing_callback(VALUE self, VALUE delta) {
    boltffi_make_incrementing_callback(NUM2INT(delta));
    return Qnil;

}
static VALUE rb_map_status(VALUE self, VALUE mapper, VALUE status) {
    int32_t _ffi_ret = boltffi_map_status((mapper), NUM2INT(status));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_make_status_flipper(VALUE self) {
    boltffi_make_status_flipper();
    return Qnil;

}
static VALUE rb_format_message_with_callback(VALUE self, VALUE formatter, VALUE scope, VALUE message) {
    Check_Type(scope, T_STRING);
    Check_Type(message, T_STRING);
    FfiBuf _ffi_ret = boltffi_format_message_with_callback((formatter), bolt_rb_to_ffi_string(scope), bolt_rb_to_ffi_string(message));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_format_message_with_boxed_callback(VALUE self, VALUE formatter, VALUE scope, VALUE message) {
    Check_Type(scope, T_STRING);
    Check_Type(message, T_STRING);
    FfiBuf _ffi_ret = boltffi_format_message_with_boxed_callback((formatter), bolt_rb_to_ffi_string(scope), bolt_rb_to_ffi_string(message));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_make_message_prefixer(VALUE self, VALUE prefix) {
    Check_Type(prefix, T_STRING);
    boltffi_make_message_prefixer(bolt_rb_to_ffi_string(prefix));
    return Qnil;

}
static VALUE rb_invoke_multi_method(VALUE self, VALUE callback, VALUE x, VALUE y) {
    int32_t _ffi_ret = boltffi_invoke_multi_method((callback), NUM2INT(x), NUM2INT(y));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_multi_method_boxed(VALUE self, VALUE callback, VALUE x, VALUE y) {
    int32_t _ffi_ret = boltffi_invoke_multi_method_boxed((callback), NUM2INT(x), NUM2INT(y));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_two_callbacks(VALUE self, VALUE first, VALUE second, VALUE value) {
    int32_t _ffi_ret = boltffi_invoke_two_callbacks((first), (second), NUM2INT(value));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_offset_callback(VALUE self, VALUE callback, VALUE value, VALUE delta) {
    int64_t _ffi_ret = boltffi_invoke_offset_callback((callback), NUM2LL(value), NUM2ULL(delta));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_invoke_boxed_offset_callback(VALUE self, VALUE callback, VALUE value, VALUE delta) {
    int64_t _ffi_ret = boltffi_invoke_boxed_offset_callback((callback), NUM2LL(value), NUM2ULL(delta));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_email(VALUE self, VALUE email) {
    boltffi_echo_email((email));
    return Qnil;

}
static VALUE rb_email_domain(VALUE self, VALUE email) {
    FfiBuf _ffi_ret = boltffi_email_domain((email));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_datetime(VALUE self, VALUE dt) {
    boltffi_echo_datetime((dt));
    return Qnil;

}
static VALUE rb_datetime_to_millis(VALUE self, VALUE dt) {
    int64_t _ffi_ret = boltffi_datetime_to_millis((dt));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_format_timestamp(VALUE self, VALUE timestamp) {
    FfiBuf _ffi_ret = boltffi_format_timestamp((timestamp));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_status(VALUE self, VALUE s) {
    int32_t _ffi_ret = boltffi_echo_status(NUM2INT(s));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_status_to_string(VALUE self, VALUE s) {
    FfiBuf _ffi_ret = boltffi_status_to_string(NUM2INT(s));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_is_active(VALUE self, VALUE s) {
    int _ffi_ret = boltffi_is_active(NUM2INT(s));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_direction(VALUE self, VALUE d) {
    int32_t _ffi_ret = boltffi_echo_direction(NUM2INT(d));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_opposite_direction(VALUE self, VALUE d) {
    int32_t _ffi_ret = boltffi_opposite_direction(NUM2INT(d));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_direction_to_degrees(VALUE self, VALUE direction) {
    int32_t _ffi_ret = boltffi_direction_to_degrees(NUM2INT(direction));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_filter(VALUE self, VALUE f) {
    int32_t _ffi_ret = boltffi_echo_filter(NUM2INT(f));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_describe_filter(VALUE self, VALUE f) {
    FfiBuf _ffi_ret = boltffi_describe_filter(NUM2INT(f));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_api_response(VALUE self, VALUE response) {
    int32_t _ffi_ret = boltffi_echo_api_response(NUM2INT(response));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_is_success(VALUE self, VALUE response) {
    int _ffi_ret = boltffi_is_success(NUM2INT(response));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_shape(VALUE self, VALUE s) {
    int32_t _ffi_ret = boltffi_echo_shape(NUM2INT(s));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_make_circle(VALUE self, VALUE radius) {
    int32_t _ffi_ret = boltffi_make_circle(NUM2DBL(radius));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_make_rectangle(VALUE self, VALUE width, VALUE height) {
    int32_t _ffi_ret = boltffi_make_rectangle(NUM2DBL(width), NUM2DBL(height));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_message(VALUE self, VALUE m) {
    int32_t _ffi_ret = boltffi_echo_message(NUM2INT(m));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_message_summary(VALUE self, VALUE m) {
    FfiBuf _ffi_ret = boltffi_message_summary(NUM2INT(m));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_animal(VALUE self, VALUE a) {
    int32_t _ffi_ret = boltffi_echo_animal(NUM2INT(a));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_animal_name(VALUE self, VALUE a) {
    FfiBuf _ffi_ret = boltffi_animal_name(NUM2INT(a));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_task_status(VALUE self, VALUE status) {
    int32_t _ffi_ret = boltffi_echo_task_status(NUM2INT(status));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_get_status_progress(VALUE self, VALUE status) {
    int32_t _ffi_ret = boltffi_get_status_progress(NUM2INT(status));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_is_status_complete(VALUE self, VALUE status) {
    int _ffi_ret = boltffi_is_status_complete(NUM2INT(status));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_lifecycle_event(VALUE self, VALUE ev) {
    int32_t _ffi_ret = boltffi_echo_lifecycle_event(NUM2INT(ev));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_make_critical_lifecycle_event(VALUE self, VALUE id) {
    int32_t _ffi_ret = boltffi_make_critical_lifecycle_event(NUM2LL(id));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_priority(VALUE self, VALUE p) {
    int32_t _ffi_ret = boltffi_echo_priority(NUM2INT(p));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_priority_label(VALUE self, VALUE p) {
    FfiBuf _ffi_ret = boltffi_priority_label(NUM2INT(p));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_is_high_priority(VALUE self, VALUE p) {
    int _ffi_ret = boltffi_is_high_priority(NUM2INT(p));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_log_level(VALUE self, VALUE level) {
    int32_t _ffi_ret = boltffi_echo_log_level(NUM2INT(level));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_should_log(VALUE self, VALUE level, VALUE min_level) {
    int _ffi_ret = boltffi_should_log(NUM2INT(level), NUM2INT(min_level));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_http_code(VALUE self, VALUE code) {
    int32_t _ffi_ret = boltffi_echo_http_code(NUM2INT(code));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_http_code_not_found(VALUE self) {
    int32_t _ffi_ret = boltffi_http_code_not_found();
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_sign(VALUE self, VALUE s) {
    int32_t _ffi_ret = boltffi_echo_sign(NUM2INT(s));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_sign_negative(VALUE self) {
    int32_t _ffi_ret = boltffi_sign_negative();
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_bool(VALUE self, VALUE v) {
    int _ffi_ret = boltffi_echo_bool(RB_TEST(v));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_negate_bool(VALUE self, VALUE v) {
    int _ffi_ret = boltffi_negate_bool(RB_TEST(v));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_echo_i8(VALUE self, VALUE v) {
    int8_t _ffi_ret = boltffi_echo_i8(NUM2INT(v));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_u8(VALUE self, VALUE v) {
    uint8_t _ffi_ret = boltffi_echo_u8(NUM2UINT(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_i16(VALUE self, VALUE v) {
    int16_t _ffi_ret = boltffi_echo_i16(NUM2INT(v));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_u16(VALUE self, VALUE v) {
    uint16_t _ffi_ret = boltffi_echo_u16(NUM2UINT(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_i32(VALUE self, VALUE v) {
    int32_t _ffi_ret = boltffi_echo_i32(NUM2INT(v));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_add_i32(VALUE self, VALUE a, VALUE b) {
    int32_t _ffi_ret = boltffi_add_i32(NUM2INT(a), NUM2INT(b));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_u32(VALUE self, VALUE v) {
    uint32_t _ffi_ret = boltffi_echo_u32(NUM2UINT(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_i64(VALUE self, VALUE v) {
    int64_t _ffi_ret = boltffi_echo_i64(NUM2LL(v));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_echo_u64(VALUE self, VALUE v) {
    uint64_t _ffi_ret = boltffi_echo_u64(NUM2ULL(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_f32(VALUE self, VALUE v) {
    float _ffi_ret = boltffi_echo_f32(NUM2DBL(v));
    return rb_float_new((double)_ffi_ret);

}
static VALUE rb_add_f32(VALUE self, VALUE a, VALUE b) {
    float _ffi_ret = boltffi_add_f32(NUM2DBL(a), NUM2DBL(b));
    return rb_float_new((double)_ffi_ret);

}
static VALUE rb_echo_f64(VALUE self, VALUE v) {
    double _ffi_ret = boltffi_echo_f64(NUM2DBL(v));
    return rb_float_new(_ffi_ret);

}
static VALUE rb_add_f64(VALUE self, VALUE a, VALUE b) {
    double _ffi_ret = boltffi_add_f64(NUM2DBL(a), NUM2DBL(b));
    return rb_float_new(_ffi_ret);

}
static VALUE rb_echo_usize(VALUE self, VALUE v) {
    uint64_t _ffi_ret = boltffi_echo_usize(NUM2ULL(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_echo_isize(VALUE self, VALUE v) {
    int64_t _ffi_ret = boltffi_echo_isize(NUM2LL(v));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_noop(VALUE self) {
    boltffi_noop();
    return Qnil;

}
static VALUE rb_add(VALUE self, VALUE a, VALUE b) {
    int32_t _ffi_ret = boltffi_add(NUM2INT(a), NUM2INT(b));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_multiply(VALUE self, VALUE a, VALUE b) {
    double _ffi_ret = boltffi_multiply(NUM2DBL(a), NUM2DBL(b));
    return rb_float_new(_ffi_ret);

}
static VALUE rb_echo_string(VALUE self, VALUE v) {
    Check_Type(v, T_STRING);
    FfiBuf _ffi_ret = boltffi_echo_string(bolt_rb_to_ffi_string(v));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_concat_strings(VALUE self, VALUE a, VALUE b) {
    Check_Type(a, T_STRING);
    Check_Type(b, T_STRING);
    FfiBuf _ffi_ret = boltffi_concat_strings(bolt_rb_to_ffi_string(a), bolt_rb_to_ffi_string(b));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_string_length(VALUE self, VALUE v) {
    Check_Type(v, T_STRING);
    uint32_t _ffi_ret = boltffi_string_length(bolt_rb_to_ffi_string(v));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_string_is_empty(VALUE self, VALUE v) {
    Check_Type(v, T_STRING);
    int _ffi_ret = boltffi_string_is_empty(bolt_rb_to_ffi_string(v));
    return _ffi_ret ? Qtrue : Qfalse;

}
static VALUE rb_repeat_string(VALUE self, VALUE v, VALUE count) {
    Check_Type(v, T_STRING);
    FfiBuf _ffi_ret = boltffi_repeat_string(bolt_rb_to_ffi_string(v), NUM2UINT(count));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_generate_string(VALUE self, VALUE size) {
    FfiBuf _ffi_ret = boltffi_generate_string(NUM2INT(size));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_echo_vec_u8(VALUE self, VALUE v) {
    Check_Type(v, T_STRING);
    FfiBuf _ffi_ret = boltffi_echo_vec_u8(bolt_rb_to_ffi_bytes(v));
    // Vec<u8> returns a raw (non-wire-encoded) FfiBuf: ptr/len describe the bytes
    // directly, with no 4-byte length prefix (unlike String's wire_encode buffer).
    { VALUE _rb_ret = rb_str_new((const char*)_ffi_ret.ptr, (long)_ffi_ret.len);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_inc_u64_value(VALUE self, VALUE value) {
    uint64_t _ffi_ret = boltffi_inc_u64_value(NUM2ULL(value));
    return rb_uint2inum((uintptr_t)_ffi_ret);

}
static VALUE rb_result_to_string(VALUE self, VALUE v) {
    FfiBuf _ffi_ret = boltffi_result_to_string((v));
    { uint32_t _wire_len = 0;
      memcpy(&_wire_len, _ffi_ret.ptr, sizeof(uint32_t));
      VALUE _rb_ret = rb_utf8_str_new((const char*)(_ffi_ret.ptr + sizeof(uint32_t)), (long)_wire_len);
      RB_ENC_CODERANGE_SET(_rb_ret, ENC_CODERANGE_VALID);
      boltffi_free_buf(_ffi_ret);
      return _rb_ret; }

}
static VALUE rb_process_value(VALUE self, VALUE value) {
    int32_t _ffi_ret = boltffi_process_value(NUM2INT(value));
    return rb_int2inum((intptr_t)_ffi_ret);

}
static VALUE rb_api_result_is_success(VALUE self, VALUE result) {
    int _ffi_ret = boltffi_api_result_is_success(NUM2INT(result));
    return _ffi_ret ? Qtrue : Qfalse;

}

void Init_demo_native(void) {
    // Declare every method defined below safe to call from any Ractor.
    // Opt-in (`[targets.ruby] ractor_safe`): asserts the bound Rust crate has no
    // unsynchronized global mutable state. Must precede the rb_define_* calls.
    rb_ext_ractor_safe(true);
    VALUE mod = rb_define_module("Demo");
    VALUE native = rb_define_module_under(mod, "Native");

    c_data_consumer = rb_define_class_under(mod, "DataConsumer", rb_cObject);
    rb_define_alloc_func(c_data_consumer, data_consumer_alloc);
    rb_define_method(c_data_consumer, "initialize", data_consumer_initialize, 0);
    rb_define_method(c_data_consumer, "set_provider", data_consumer_set_provider, 1);
    rb_define_method(c_data_consumer, "compute_sum", data_consumer_compute_sum, 0);

    c_async_worker = rb_define_class_under(mod, "AsyncWorker", rb_cObject);
    rb_define_alloc_func(c_async_worker, async_worker_alloc);
    rb_define_method(c_async_worker, "initialize", async_worker_initialize, 1);
    rb_define_method(c_async_worker, "get_prefix", async_worker_get_prefix, 0);

    c_constructor_coverage_matrix = rb_define_class_under(mod, "ConstructorCoverageMatrix", rb_cObject);
    rb_define_alloc_func(c_constructor_coverage_matrix, constructor_coverage_matrix_alloc);
    rb_define_method(c_constructor_coverage_matrix, "initialize", constructor_coverage_matrix_initialize, 0);
    rb_define_singleton_method(c_constructor_coverage_matrix, "with_scalar_mix", constructor_coverage_matrix_ctor_with_scalar_mix, 3);
    rb_define_singleton_method(c_constructor_coverage_matrix, "with_string_and_bytes", constructor_coverage_matrix_ctor_with_string_and_bytes, 2);
    rb_define_method(c_constructor_coverage_matrix, "constructor_variant", constructor_coverage_matrix_constructor_variant, 0);
    rb_define_method(c_constructor_coverage_matrix, "summary", constructor_coverage_matrix_summary, 0);
    rb_define_method(c_constructor_coverage_matrix, "payload_checksum", constructor_coverage_matrix_payload_checksum, 0);
    rb_define_method(c_constructor_coverage_matrix, "vector_count", constructor_coverage_matrix_vector_count, 0);

    c_inventory = rb_define_class_under(mod, "Inventory", rb_cObject);
    rb_define_alloc_func(c_inventory, inventory_alloc);
    rb_define_method(c_inventory, "initialize", inventory_initialize, 0);
    rb_define_singleton_method(c_inventory, "with_capacity", inventory_ctor_with_capacity, 1);
    rb_define_singleton_method(c_inventory, "try_new", inventory_ctor_try_new, 1);
    rb_define_method(c_inventory, "count", inventory_count, 0);
    rb_define_method(c_inventory, "capacity", inventory_capacity, 0);
    rb_define_method(c_inventory, "add", inventory_add, 1);

    c_counter = rb_define_class_under(mod, "Counter", rb_cObject);
    rb_define_alloc_func(c_counter, counter_alloc);
    rb_define_method(c_counter, "initialize", counter_initialize, 1);
    rb_define_method(c_counter, "get", counter_get, 0);
    rb_define_method(c_counter, "increment", counter_increment, 0);
    rb_define_method(c_counter, "add", counter_add, 1);
    rb_define_method(c_counter, "reset", counter_reset, 0);

    c_mixed_record_service = rb_define_class_under(mod, "MixedRecordService", rb_cObject);
    rb_define_alloc_func(c_mixed_record_service, mixed_record_service_alloc);
    rb_define_method(c_mixed_record_service, "initialize", mixed_record_service_initialize, 1);
    rb_define_method(c_mixed_record_service, "get_label", mixed_record_service_get_label, 0);
    rb_define_method(c_mixed_record_service, "stored_count", mixed_record_service_stored_count, 0);

    c_math_utils = rb_define_class_under(mod, "MathUtils", rb_cObject);
    rb_define_alloc_func(c_math_utils, math_utils_alloc);
    rb_define_method(c_math_utils, "initialize", math_utils_initialize, 1);
    rb_define_method(c_math_utils, "round", math_utils_round, 1);
    rb_define_singleton_method(c_math_utils, "add", math_utils_add, 2);
    rb_define_singleton_method(c_math_utils, "clamp", math_utils_clamp, 3);

    c_event_bus = rb_define_class_under(mod, "EventBus", rb_cObject);
    rb_define_alloc_func(c_event_bus, event_bus_alloc);
    rb_define_method(c_event_bus, "initialize", event_bus_initialize, 0);
    rb_define_method(c_event_bus, "emit_value", event_bus_emit_value, 1);

    c_shared_counter = rb_define_class_under(mod, "SharedCounter", rb_cObject);
    rb_define_alloc_func(c_shared_counter, shared_counter_alloc);
    rb_define_method(c_shared_counter, "initialize", shared_counter_initialize, 1);
    rb_define_method(c_shared_counter, "get", shared_counter_get, 0);
    rb_define_method(c_shared_counter, "set", shared_counter_set, 1);
    rb_define_method(c_shared_counter, "increment", shared_counter_increment, 0);
    rb_define_method(c_shared_counter, "add", shared_counter_add, 1);

    c_data_store = rb_define_class_under(mod, "DataStore", rb_cObject);
    rb_define_alloc_func(c_data_store, data_store_alloc);
    rb_define_method(c_data_store, "initialize", data_store_initialize, 0);
    rb_define_singleton_method(c_data_store, "with_sample_data", data_store_ctor_with_sample_data, 0);
    rb_define_singleton_method(c_data_store, "with_capacity", data_store_ctor_with_capacity, 1);
    rb_define_singleton_method(c_data_store, "with_initial_point", data_store_ctor_with_initial_point, 3);
    rb_define_method(c_data_store, "add_parts", data_store_add_parts, 3);
    rb_define_method(c_data_store, "len", data_store_len, 0);
    rb_define_method(c_data_store, "is_empty", data_store_is_empty, 0);
    rb_define_method(c_data_store, "sum", data_store_sum, 0);
    rb_define_method(c_data_store, "foreach", data_store_foreach, 1);

    c_accumulator = rb_define_class_under(mod, "Accumulator", rb_cObject);
    rb_define_alloc_func(c_accumulator, accumulator_alloc);
    rb_define_method(c_accumulator, "initialize", accumulator_initialize, 0);
    rb_define_method(c_accumulator, "add", accumulator_add, 1);
    rb_define_method(c_accumulator, "get", accumulator_get, 0);
    rb_define_method(c_accumulator, "reset", accumulator_reset, 0);

    c_marker = rb_define_class_under(mod, "Marker", rb_cObject);
    rb_define_alloc_func(c_marker, marker_alloc);
    rb_define_method(c_marker, "id", marker_id, 0);
    rb_define_method(c_marker, "title", marker_title, 0);

    c_map_view = rb_define_class_under(mod, "MapView", rb_cObject);
    rb_define_alloc_func(c_map_view, map_view_alloc);
    rb_define_method(c_map_view, "initialize", map_view_initialize, 0);
    rb_define_method(c_map_view, "marker_count", map_view_marker_count, 0);

    c_state_holder = rb_define_class_under(mod, "StateHolder", rb_cObject);
    rb_define_alloc_func(c_state_holder, state_holder_alloc);
    rb_define_method(c_state_holder, "initialize", state_holder_initialize, 1);
    rb_define_method(c_state_holder, "get_label", state_holder_get_label, 0);
    rb_define_method(c_state_holder, "get_value", state_holder_get_value, 0);
    rb_define_method(c_state_holder, "item_count", state_holder_item_count, 0);

    c_counter_single_threaded = rb_define_class_under(mod, "CounterSingleThreaded", rb_cObject);
    rb_define_alloc_func(c_counter_single_threaded, counter_single_threaded_alloc);
    rb_define_method(c_counter_single_threaded, "initialize", counter_single_threaded_initialize, 0);
    rb_define_method(c_counter_single_threaded, "get", counter_single_threaded_get, 0);

    c_accumulator_single_threaded = rb_define_class_under(mod, "AccumulatorSingleThreaded", rb_cObject);
    rb_define_alloc_func(c_accumulator_single_threaded, accumulator_single_threaded_alloc);
    rb_define_method(c_accumulator_single_threaded, "initialize", accumulator_single_threaded_initialize, 0);
    rb_define_method(c_accumulator_single_threaded, "get", accumulator_single_threaded_get, 0);


    rb_define_module_function(native, "echo_duration", rb_echo_duration, 1);
    rb_define_module_function(native, "make_duration", rb_make_duration, 2);
    rb_define_module_function(native, "duration_as_millis", rb_duration_as_millis, 1);
    rb_define_module_function(native, "echo_system_time", rb_echo_system_time, 1);
    rb_define_module_function(native, "system_time_to_millis", rb_system_time_to_millis, 1);
    rb_define_module_function(native, "millis_to_system_time", rb_millis_to_system_time, 1);
    rb_define_module_function(native, "echo_uuid", rb_echo_uuid, 1);
    rb_define_module_function(native, "uuid_to_string", rb_uuid_to_string, 1);
    rb_define_module_function(native, "echo_url", rb_echo_url, 1);
    rb_define_module_function(native, "url_to_string", rb_url_to_string, 1);
    rb_define_module_function(native, "echo_bytes", rb_echo_bytes, 1);
    rb_define_module_function(native, "bytes_length", rb_bytes_length, 1);
    rb_define_module_function(native, "bytes_sum", rb_bytes_sum, 1);
    rb_define_module_function(native, "make_bytes", rb_make_bytes, 1);
    rb_define_module_function(native, "reverse_bytes", rb_reverse_bytes, 1);
    rb_define_module_function(native, "generate_bytes", rb_generate_bytes, 1);
    rb_define_module_function(native, "apply_closure", rb_apply_closure, 2);
    rb_define_module_function(native, "apply_binary_closure", rb_apply_binary_closure, 3);
    rb_define_module_function(native, "apply_void_closure", rb_apply_void_closure, 2);
    rb_define_module_function(native, "apply_nullary_closure", rb_apply_nullary_closure, 1);
    rb_define_module_function(native, "apply_string_closure", rb_apply_string_closure, 2);
    rb_define_module_function(native, "apply_bool_closure", rb_apply_bool_closure, 2);
    rb_define_module_function(native, "apply_f64_closure", rb_apply_f64_closure, 2);
    rb_define_module_function(native, "apply_offset_closure", rb_apply_offset_closure, 3);
    rb_define_module_function(native, "apply_status_closure", rb_apply_status_closure, 2);
    rb_define_module_function(native, "invoke_value_callback", rb_invoke_value_callback, 2);
    rb_define_module_function(native, "invoke_value_callback_twice", rb_invoke_value_callback_twice, 3);
    rb_define_module_function(native, "invoke_boxed_value_callback", rb_invoke_boxed_value_callback, 2);
    rb_define_module_function(native, "make_incrementing_callback", rb_make_incrementing_callback, 1);
    rb_define_module_function(native, "map_status", rb_map_status, 2);
    rb_define_module_function(native, "make_status_flipper", rb_make_status_flipper, 0);
    rb_define_module_function(native, "format_message_with_callback", rb_format_message_with_callback, 3);
    rb_define_module_function(native, "format_message_with_boxed_callback", rb_format_message_with_boxed_callback, 3);
    rb_define_module_function(native, "make_message_prefixer", rb_make_message_prefixer, 1);
    rb_define_module_function(native, "invoke_multi_method", rb_invoke_multi_method, 3);
    rb_define_module_function(native, "invoke_multi_method_boxed", rb_invoke_multi_method_boxed, 3);
    rb_define_module_function(native, "invoke_two_callbacks", rb_invoke_two_callbacks, 3);
    rb_define_module_function(native, "invoke_offset_callback", rb_invoke_offset_callback, 3);
    rb_define_module_function(native, "invoke_boxed_offset_callback", rb_invoke_boxed_offset_callback, 3);
    rb_define_module_function(native, "echo_email", rb_echo_email, 1);
    rb_define_module_function(native, "email_domain", rb_email_domain, 1);
    rb_define_module_function(native, "echo_datetime", rb_echo_datetime, 1);
    rb_define_module_function(native, "datetime_to_millis", rb_datetime_to_millis, 1);
    rb_define_module_function(native, "format_timestamp", rb_format_timestamp, 1);
    rb_define_module_function(native, "echo_status", rb_echo_status, 1);
    rb_define_module_function(native, "status_to_string", rb_status_to_string, 1);
    rb_define_module_function(native, "is_active", rb_is_active, 1);
    rb_define_module_function(native, "echo_direction", rb_echo_direction, 1);
    rb_define_module_function(native, "opposite_direction", rb_opposite_direction, 1);
    rb_define_module_function(native, "direction_to_degrees", rb_direction_to_degrees, 1);
    rb_define_module_function(native, "echo_filter", rb_echo_filter, 1);
    rb_define_module_function(native, "describe_filter", rb_describe_filter, 1);
    rb_define_module_function(native, "echo_api_response", rb_echo_api_response, 1);
    rb_define_module_function(native, "is_success", rb_is_success, 1);
    rb_define_module_function(native, "echo_shape", rb_echo_shape, 1);
    rb_define_module_function(native, "make_circle", rb_make_circle, 1);
    rb_define_module_function(native, "make_rectangle", rb_make_rectangle, 2);
    rb_define_module_function(native, "echo_message", rb_echo_message, 1);
    rb_define_module_function(native, "message_summary", rb_message_summary, 1);
    rb_define_module_function(native, "echo_animal", rb_echo_animal, 1);
    rb_define_module_function(native, "animal_name", rb_animal_name, 1);
    rb_define_module_function(native, "echo_task_status", rb_echo_task_status, 1);
    rb_define_module_function(native, "get_status_progress", rb_get_status_progress, 1);
    rb_define_module_function(native, "is_status_complete", rb_is_status_complete, 1);
    rb_define_module_function(native, "echo_lifecycle_event", rb_echo_lifecycle_event, 1);
    rb_define_module_function(native, "make_critical_lifecycle_event", rb_make_critical_lifecycle_event, 1);
    rb_define_module_function(native, "echo_priority", rb_echo_priority, 1);
    rb_define_module_function(native, "priority_label", rb_priority_label, 1);
    rb_define_module_function(native, "is_high_priority", rb_is_high_priority, 1);
    rb_define_module_function(native, "echo_log_level", rb_echo_log_level, 1);
    rb_define_module_function(native, "should_log", rb_should_log, 2);
    rb_define_module_function(native, "echo_http_code", rb_echo_http_code, 1);
    rb_define_module_function(native, "http_code_not_found", rb_http_code_not_found, 0);
    rb_define_module_function(native, "echo_sign", rb_echo_sign, 1);
    rb_define_module_function(native, "sign_negative", rb_sign_negative, 0);
    rb_define_module_function(native, "echo_bool", rb_echo_bool, 1);
    rb_define_module_function(native, "negate_bool", rb_negate_bool, 1);
    rb_define_module_function(native, "echo_i8", rb_echo_i8, 1);
    rb_define_module_function(native, "echo_u8", rb_echo_u8, 1);
    rb_define_module_function(native, "echo_i16", rb_echo_i16, 1);
    rb_define_module_function(native, "echo_u16", rb_echo_u16, 1);
    rb_define_module_function(native, "echo_i32", rb_echo_i32, 1);
    rb_define_module_function(native, "add_i32", rb_add_i32, 2);
    rb_define_module_function(native, "echo_u32", rb_echo_u32, 1);
    rb_define_module_function(native, "echo_i64", rb_echo_i64, 1);
    rb_define_module_function(native, "echo_u64", rb_echo_u64, 1);
    rb_define_module_function(native, "echo_f32", rb_echo_f32, 1);
    rb_define_module_function(native, "add_f32", rb_add_f32, 2);
    rb_define_module_function(native, "echo_f64", rb_echo_f64, 1);
    rb_define_module_function(native, "add_f64", rb_add_f64, 2);
    rb_define_module_function(native, "echo_usize", rb_echo_usize, 1);
    rb_define_module_function(native, "echo_isize", rb_echo_isize, 1);
    rb_define_module_function(native, "noop", rb_noop, 0);
    rb_define_module_function(native, "add", rb_add, 2);
    rb_define_module_function(native, "multiply", rb_multiply, 2);
    rb_define_module_function(native, "echo_string", rb_echo_string, 1);
    rb_define_module_function(native, "concat_strings", rb_concat_strings, 2);
    rb_define_module_function(native, "string_length", rb_string_length, 1);
    rb_define_module_function(native, "string_is_empty", rb_string_is_empty, 1);
    rb_define_module_function(native, "repeat_string", rb_repeat_string, 2);
    rb_define_module_function(native, "generate_string", rb_generate_string, 1);
    rb_define_module_function(native, "echo_vec_u8", rb_echo_vec_u8, 1);
    rb_define_module_function(native, "inc_u64_value", rb_inc_u64_value, 1);
    rb_define_module_function(native, "result_to_string", rb_result_to_string, 1);
    rb_define_module_function(native, "process_value", rb_process_value, 1);
    rb_define_module_function(native, "api_result_is_success", rb_api_result_is_success, 1);

}