# frozen_string_literal: true
# Generated by BoltFFI — do not edit.

require_relative "demo_native"

module Demo

  class StreamMessage

    attr_reader :text, :values

    def initialize(text, values)

      @text = text

      @values = values

    end
  end

  class MarkerOptions

    attr_reader :id, :title

    def initialize(id, title)

      @id = id

      @title = title

    end
  end

  class Event

    attr_reader :name, :timestamp

    def initialize(name, timestamp)

      @name = name

      @timestamp = timestamp

    end
  end

  class Point

    attr_reader :x, :y

    def initialize(x, y)

      @x = x

      @y = y

    end
  end

  class Color

    attr_reader :r, :g, :b, :a

    def initialize(r, g, b, a)

      @r = r

      @g = g

      @b = b

      @a = a

    end
  end

  class Location

    attr_reader :id, :lat, :lng, :rating, :review_count, :is_open

    def initialize(id, lat, lng, rating, review_count, is_open)

      @id = id

      @lat = lat

      @lng = lng

      @rating = rating

      @review_count = review_count

      @is_open = is_open

    end
  end

  class Trade

    attr_reader :id, :symbol_id, :price, :quantity, :bid, :ask, :volume, :timestamp, :is_buy

    def initialize(id, symbol_id, price, quantity, bid, ask, volume, timestamp, is_buy)

      @id = id

      @symbol_id = symbol_id

      @price = price

      @quantity = quantity

      @bid = bid

      @ask = ask

      @volume = volume

      @timestamp = timestamp

      @is_buy = is_buy

    end
  end

  class Particle

    attr_reader :id, :x, :y, :z, :vx, :vy, :vz, :mass, :charge, :active

    def initialize(id, x, y, z, vx, vy, vz, mass, charge, active)

      @id = id

      @x = x

      @y = y

      @z = z

      @vx = vx

      @vy = vy

      @vz = vz

      @mass = mass

      @charge = charge

      @active = active

    end
  end

  class SensorReading

    attr_reader :sensor_id, :timestamp, :temperature, :humidity, :pressure, :light, :battery, :signal_strength, :is_valid

    def initialize(sensor_id, timestamp, temperature, humidity, pressure, light, battery, signal_strength, is_valid)

      @sensor_id = sensor_id

      @timestamp = timestamp

      @temperature = temperature

      @humidity = humidity

      @pressure = pressure

      @light = light

      @battery = battery

      @signal_strength = signal_strength

      @is_valid = is_valid

    end
  end

  class DataPoint

    attr_reader :x, :y, :timestamp

    def initialize(x, y, timestamp)

      @x = x

      @y = y

      @timestamp = timestamp

    end
  end

  class ServiceConfig

    attr_reader :name, :retries, :region, :endpoint, :backup_endpoint

    def initialize(name, retries, region, endpoint, backup_endpoint)

      @name = name

      @retries = retries

      @region = region

      @endpoint = endpoint

      @backup_endpoint = backup_endpoint

    end
  end

  class MixedRecordParameters

    attr_reader :tags, :checkpoints, :fallback_anchor, :max_retries, :preview_only

    def initialize(tags, checkpoints, fallback_anchor, max_retries, preview_only)

      @tags = tags

      @checkpoints = checkpoints

      @fallback_anchor = fallback_anchor

      @max_retries = max_retries

      @preview_only = preview_only

    end
  end

  class MixedRecord

    attr_reader :name, :anchor, :priority, :shape, :parameters

    def initialize(name, anchor, priority, shape, parameters)

      @name = name

      @anchor = anchor

      @priority = priority

      @shape = shape

      @parameters = parameters

    end
  end

  class Line

    attr_reader :start, :end_

    def initialize(start, end_)

      @start = start

      @end_ = end_

    end
  end

  class Dimensions

    attr_reader :width, :height

    def initialize(width, height)

      @width = width

      @height = height

    end
  end

  class Rect

    attr_reader :origin, :dimensions

    def initialize(origin, dimensions)

      @origin = origin

      @dimensions = dimensions

    end
  end

  class Polygon

    attr_reader :points

    def initialize(points)

      @points = points

    end
  end

  class Team

    attr_reader :name, :members

    def initialize(name, members)

      @name = name

      @members = members

    end
  end

  class Classroom

    attr_reader :students

    def initialize(students)

      @students = students

    end
  end

  class TaggedScores

    attr_reader :label, :scores

    def initialize(label, scores)

      @label = label

      @scores = scores

    end
  end

  class BenchmarkUserProfile

    attr_reader :id, :name, :email, :bio, :age, :score, :tags, :scores, :is_active

    def initialize(id, name, email, bio, age, score, tags, scores, is_active)

      @id = id

      @name = name

      @email = email

      @bio = bio

      @age = age

      @score = score

      @tags = tags

      @scores = scores

      @is_active = is_active

    end
  end

  class Task

    attr_reader :title, :priority, :completed

    def initialize(title, priority, completed)

      @title = title

      @priority = priority

      @completed = completed

    end
  end

  class Notification

    attr_reader :message, :priority, :read

    def initialize(message, priority, read)

      @message = message

      @priority = priority

      @read = read

    end
  end

  class Holder

    attr_reader :shape

    def initialize(shape)

      @shape = shape

    end
  end

  class TaskHeader

    attr_reader :id, :priority, :completed

    def initialize(id, priority, completed)

      @id = id

      @priority = priority

      @completed = completed

    end
  end

  class LogEntry

    attr_reader :timestamp, :level, :code

    def initialize(timestamp, level, code)

      @timestamp = timestamp

      @level = level

      @code = code

    end
  end

  class UserProfile

    attr_reader :name, :age, :email, :score

    def initialize(name, age, email, score)

      @name = name

      @age = age

      @email = email

      @score = score

    end
  end

  class SearchResult

    attr_reader :query, :total, :next_cursor, :max_score

    def initialize(query, total, next_cursor, max_score)

      @query = query

      @total = total

      @next_cursor = next_cursor

      @max_score = max_score

    end
  end

  class Person

    attr_reader :name, :age

    def initialize(name, age)

      @name = name

      @age = age

    end
  end

  class Address

    attr_reader :street, :city, :zip

    def initialize(street, city, zip)

      @street = street

      @city = city

      @zip = zip

    end
  end

  class AppError < StandardError

    attr_reader :code, :message

    def initialize(code, message)

      @code = code

      @message = message

    end
  end

  class BenchmarkResponse

    attr_reader :request_id, :result

    def initialize(request_id, result)

      @request_id = request_id

      @result = result

    end
  end


  module Status

    ACTIVE = 0

    INACTIVE = 1

    PENDING = 2

  end

  module Direction

    NORTH = 0

    SOUTH = 1

    EAST = 2

    WEST = 3

  end

  module Filter

    NONE = 0

    BY_NAME = 1

    BY_RANGE = 2

    BY_TAGS = 3

    BY_GROUPS = 4

    BY_POINTS = 5

  end

  module ApiResponse

    SUCCESS = 0

    ERROR = 1

    REDIRECT = 2

    EMPTY = 3

  end

  module Shape

    CIRCLE = 0

    RECTANGLE = 1

    TRIANGLE = 2

    POINT = 3

    APEX = 4

    CLUSTER = 5

  end

  module Message

    TEXT = 0

    IMAGE = 1

    PING = 2

  end

  module Animal

    DOG = 0

    CAT = 1

    FISH = 2

  end

  module TaskStatus

    PENDING = 0

    IN_PROGRESS = 1

    COMPLETED = 2

    FAILED = 3

  end

  module LifecycleEvent

    TASK_STARTED = 0

    TICK = 1

  end

  module Priority

    LOW = 0

    MEDIUM = 1

    HIGH = 2

    CRITICAL = 3

  end

  module LogLevel

    TRACE = 0

    DEBUG = 1

    INFO = 2

    WARN = 3

    ERROR = 4

  end

  module HttpCode

    OK = 200

    NOT_FOUND = 404

    SERVER_ERROR = 500

  end

  module Sign

    NEGATIVE = -1

    ZERO = 0

    POSITIVE = 1

  end

  module MathError

    DIVISION_BY_ZERO = 0

    NEGATIVE_INPUT = 1

    OVERFLOW = 2

  end

  module ValidationError

    TOO_SHORT = 1

    TOO_LONG = 2

    INVALID_FORMAT = 3

  end

  module ApiResult

    SUCCESS = 0

    ERROR_CODE = 1

    ERROR_WITH_DATA = 2

  end

  module ComputeError

    INVALID_INPUT = 0

    OVERFLOW = 1

  end


  module_function def echo_duration(d)
    Native.echo_duration(d)
  end

  module_function def make_duration(secs, nanos)
    Native.make_duration(secs, nanos)
  end

  module_function def duration_as_millis(d)
    Native.duration_as_millis(d)
  end

  module_function def echo_system_time(t)
    Native.echo_system_time(t)
  end

  module_function def system_time_to_millis(t)
    Native.system_time_to_millis(t)
  end

  module_function def millis_to_system_time(millis)
    Native.millis_to_system_time(millis)
  end

  module_function def echo_uuid(id)
    Native.echo_uuid(id)
  end

  module_function def uuid_to_string(id)
    Native.uuid_to_string(id)
  end

  module_function def echo_url(url)
    Native.echo_url(url)
  end

  module_function def url_to_string(url)
    Native.url_to_string(url)
  end

  module_function def echo_bytes(data)
    Native.echo_bytes(data)
  end

  module_function def bytes_length(data)
    Native.bytes_length(data)
  end

  module_function def bytes_sum(data)
    Native.bytes_sum(data)
  end

  module_function def make_bytes(len)
    Native.make_bytes(len)
  end

  module_function def reverse_bytes(data)
    Native.reverse_bytes(data)
  end

  module_function def generate_bytes(size)
    Native.generate_bytes(size)
  end

  module_function def apply_closure(f, value)
    Native.apply_closure(f, value)
  end

  module_function def apply_binary_closure(f, a, b)
    Native.apply_binary_closure(f, a, b)
  end

  module_function def apply_void_closure(f, value)
    Native.apply_void_closure(f, value)
  end

  module_function def apply_nullary_closure(f)
    Native.apply_nullary_closure(f)
  end

  module_function def apply_string_closure(f, s)
    Native.apply_string_closure(f, s)
  end

  module_function def apply_bool_closure(f, v)
    Native.apply_bool_closure(f, v)
  end

  module_function def apply_f64_closure(f, v)
    Native.apply_f64_closure(f, v)
  end

  module_function def apply_offset_closure(f, value, delta)
    Native.apply_offset_closure(f, value, delta)
  end

  module_function def apply_status_closure(f, status)
    Native.apply_status_closure(f, status)
  end

  module_function def invoke_value_callback(callback, input)
    Native.invoke_value_callback(callback, input)
  end

  module_function def invoke_value_callback_twice(callback, a, b)
    Native.invoke_value_callback_twice(callback, a, b)
  end

  module_function def invoke_boxed_value_callback(callback, input)
    Native.invoke_boxed_value_callback(callback, input)
  end

  module_function def make_incrementing_callback(delta)
    Native.make_incrementing_callback(delta)
  end

  module_function def map_status(mapper, status)
    Native.map_status(mapper, status)
  end

  module_function def make_status_flipper()
    Native.make_status_flipper()
  end

  module_function def format_message_with_callback(formatter, scope, message)
    Native.format_message_with_callback(formatter, scope, message)
  end

  module_function def format_message_with_boxed_callback(formatter, scope, message)
    Native.format_message_with_boxed_callback(formatter, scope, message)
  end

  module_function def make_message_prefixer(prefix)
    Native.make_message_prefixer(prefix)
  end

  module_function def invoke_multi_method(callback, x, y)
    Native.invoke_multi_method(callback, x, y)
  end

  module_function def invoke_multi_method_boxed(callback, x, y)
    Native.invoke_multi_method_boxed(callback, x, y)
  end

  module_function def invoke_two_callbacks(first, second, value)
    Native.invoke_two_callbacks(first, second, value)
  end

  module_function def invoke_offset_callback(callback, value, delta)
    Native.invoke_offset_callback(callback, value, delta)
  end

  module_function def invoke_boxed_offset_callback(callback, value, delta)
    Native.invoke_boxed_offset_callback(callback, value, delta)
  end

  module_function def echo_email(email)
    Native.echo_email(email)
  end

  module_function def email_domain(email)
    Native.email_domain(email)
  end

  module_function def echo_datetime(dt)
    Native.echo_datetime(dt)
  end

  module_function def datetime_to_millis(dt)
    Native.datetime_to_millis(dt)
  end

  module_function def format_timestamp(timestamp)
    Native.format_timestamp(timestamp)
  end

  module_function def echo_status(s)
    Native.echo_status(s)
  end

  module_function def status_to_string(s)
    Native.status_to_string(s)
  end

  module_function def is_active(s)
    Native.is_active(s)
  end

  module_function def echo_direction(d)
    Native.echo_direction(d)
  end

  module_function def opposite_direction(d)
    Native.opposite_direction(d)
  end

  module_function def direction_to_degrees(direction)
    Native.direction_to_degrees(direction)
  end

  module_function def echo_filter(f)
    Native.echo_filter(f)
  end

  module_function def describe_filter(f)
    Native.describe_filter(f)
  end

  module_function def echo_api_response(response)
    Native.echo_api_response(response)
  end

  module_function def is_success(response)
    Native.is_success(response)
  end

  module_function def echo_shape(s)
    Native.echo_shape(s)
  end

  module_function def make_circle(radius)
    Native.make_circle(radius)
  end

  module_function def make_rectangle(width, height)
    Native.make_rectangle(width, height)
  end

  module_function def echo_message(m)
    Native.echo_message(m)
  end

  module_function def message_summary(m)
    Native.message_summary(m)
  end

  module_function def echo_animal(a)
    Native.echo_animal(a)
  end

  module_function def animal_name(a)
    Native.animal_name(a)
  end

  module_function def echo_task_status(status)
    Native.echo_task_status(status)
  end

  module_function def get_status_progress(status)
    Native.get_status_progress(status)
  end

  module_function def is_status_complete(status)
    Native.is_status_complete(status)
  end

  module_function def echo_lifecycle_event(ev)
    Native.echo_lifecycle_event(ev)
  end

  module_function def make_critical_lifecycle_event(id)
    Native.make_critical_lifecycle_event(id)
  end

  module_function def echo_priority(p)
    Native.echo_priority(p)
  end

  module_function def priority_label(p)
    Native.priority_label(p)
  end

  module_function def is_high_priority(p)
    Native.is_high_priority(p)
  end

  module_function def echo_log_level(level)
    Native.echo_log_level(level)
  end

  module_function def should_log(level, min_level)
    Native.should_log(level, min_level)
  end

  module_function def echo_http_code(code)
    Native.echo_http_code(code)
  end

  module_function def http_code_not_found()
    Native.http_code_not_found()
  end

  module_function def echo_sign(s)
    Native.echo_sign(s)
  end

  module_function def sign_negative()
    Native.sign_negative()
  end

  module_function def echo_bool(v)
    Native.echo_bool(v)
  end

  module_function def negate_bool(v)
    Native.negate_bool(v)
  end

  module_function def echo_i8(v)
    Native.echo_i8(v)
  end

  module_function def echo_u8(v)
    Native.echo_u8(v)
  end

  module_function def echo_i16(v)
    Native.echo_i16(v)
  end

  module_function def echo_u16(v)
    Native.echo_u16(v)
  end

  module_function def echo_i32(v)
    Native.echo_i32(v)
  end

  module_function def add_i32(a, b)
    Native.add_i32(a, b)
  end

  module_function def echo_u32(v)
    Native.echo_u32(v)
  end

  module_function def echo_i64(v)
    Native.echo_i64(v)
  end

  module_function def echo_u64(v)
    Native.echo_u64(v)
  end

  module_function def echo_f32(v)
    Native.echo_f32(v)
  end

  module_function def add_f32(a, b)
    Native.add_f32(a, b)
  end

  module_function def echo_f64(v)
    Native.echo_f64(v)
  end

  module_function def add_f64(a, b)
    Native.add_f64(a, b)
  end

  module_function def echo_usize(v)
    Native.echo_usize(v)
  end

  module_function def echo_isize(v)
    Native.echo_isize(v)
  end

  module_function def noop()
    Native.noop()
  end

  module_function def add(a, b)
    Native.add(a, b)
  end

  module_function def multiply(a, b)
    Native.multiply(a, b)
  end

  module_function def echo_string(v)
    Native.echo_string(v)
  end

  module_function def concat_strings(a, b)
    Native.concat_strings(a, b)
  end

  module_function def string_length(v)
    Native.string_length(v)
  end

  module_function def string_is_empty(v)
    Native.string_is_empty(v)
  end

  module_function def repeat_string(v, count)
    Native.repeat_string(v, count)
  end

  module_function def generate_string(size)
    Native.generate_string(size)
  end

  module_function def echo_vec_u8(v)
    Native.echo_vec_u8(v)
  end

  module_function def inc_u64_value(value)
    Native.inc_u64_value(value)
  end

  module_function def result_to_string(v)
    Native.result_to_string(v)
  end

  module_function def process_value(value)
    Native.process_value(value)
  end

  module_function def api_result_is_success(result)
    Native.api_result_is_success(result)
  end

end